# Form implementation generated from reading ui file 'screens\Buy.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuyDialog(object):
    def setupUi(self, BuyDialog):
        BuyDialog.setObjectName("BuyDialog")
        BuyDialog.resize(513, 419)
        BuyDialog.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")
        self.txtCod = QtWidgets.QLineEdit(parent=BuyDialog)
        self.txtCod.setEnabled(True)
        self.txtCod.setGeometry(QtCore.QRect(60, 60, 171, 41))
        self.txtCod.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0,0,0,0.3); \n"
"    color: #e0ffe0;\n"
"    font-size: 16px;\n"
"    border: 1px solid #77dd77;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #aaffaa;\n"
"    font-style: italic;\n"
"}")
        self.txtCod.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.txtCod.setObjectName("txtCod")
        self.lblAmountBuy = QtWidgets.QLabel(parent=BuyDialog)
        self.lblAmountBuy.setGeometry(QtCore.QRect(60, 120, 281, 21))
        self.lblAmountBuy.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.lblAmountBuy.setObjectName("lblAmountBuy")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=BuyDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 220, 421, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblBalance = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBalance.sizePolicy().hasHeightForWidth())
        self.lblBalance.setSizePolicy(sizePolicy)
        self.lblBalance.setAutoFillBackground(False)
        self.lblBalance.setStyleSheet("QLabel {\n"
"    color: #77dd77;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"    qproperty-alignment: \'AlignLeft | AlignVCenter\';\n"
"}\n"
"")
        self.lblBalance.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lblBalance.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblBalance.setWordWrap(True)
        self.lblBalance.setObjectName("lblBalance")
        self.verticalLayout.addWidget(self.lblBalance)
        self.lblValidBuy = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblValidBuy.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblValidBuy.sizePolicy().hasHeightForWidth())
        self.lblValidBuy.setSizePolicy(sizePolicy)
        self.lblValidBuy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.lblValidBuy.setStyleSheet("QLabel {\n"
"    color: #ff5555;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: \'AlignLeft | AlignVCenter\';\n"
"}")
        self.lblValidBuy.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.LatinAmerica))
        self.lblValidBuy.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblValidBuy.setWordWrap(True)
        self.lblValidBuy.setObjectName("lblValidBuy")
        self.verticalLayout.addWidget(self.lblValidBuy)
        self.lblCodBuy = QtWidgets.QLabel(parent=BuyDialog)
        self.lblCodBuy.setGeometry(QtCore.QRect(60, 30, 321, 21))
        self.lblCodBuy.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.lblCodBuy.setObjectName("lblCodBuy")
        self.btnBuy = QtWidgets.QPushButton(parent=BuyDialog)
        self.btnBuy.setGeometry(QtCore.QRect(60, 340, 331, 41))
        self.btnBuy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnBuy.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnBuy.setObjectName("btnBuy")
        self.txtAmount = QtWidgets.QLineEdit(parent=BuyDialog)
        self.txtAmount.setEnabled(True)
        self.txtAmount.setGeometry(QtCore.QRect(60, 150, 171, 41))
        self.txtAmount.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0,0,0,0.3); \n"
"    color: #e0ffe0;\n"
"    font-size: 16px;\n"
"    border: 1px solid #77dd77;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #aaffaa;\n"
"    font-style: italic;\n"
"}")
        self.txtAmount.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.txtAmount.setObjectName("txtAmount")

        self.retranslateUi(BuyDialog)
        QtCore.QMetaObject.connectSlotsByName(BuyDialog)

    def retranslateUi(self, BuyDialog):
        _translate = QtCore.QCoreApplication.translate
        BuyDialog.setWindowTitle(_translate("BuyDialog", "Dialog"))
        self.txtCod.setPlaceholderText(_translate("BuyDialog", "COD"))
        self.lblAmountBuy.setText(_translate("BuyDialog", "Ingrese el monto que desea comprar"))
        self.lblBalance.setText(_translate("BuyDialog", "Saldo actual en ARS:"))
        self.lblValidBuy.setText(_translate("BuyDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">TextLabel</span></p></body></html>"))
        self.lblCodBuy.setText(_translate("BuyDialog", "Ingrese el codigo de la moneda a comprar"))
        self.btnBuy.setText(_translate("BuyDialog", "Comprar"))
        self.txtAmount.setPlaceholderText(_translate("BuyDialog", "$"))
