# Form implementation generated from reading ui file 'screens\CreateAcc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateAccDialog(object):
    def setupUi(self, CreateAccDialog):
        CreateAccDialog.setObjectName("CreateAccDialog")
        CreateAccDialog.resize(512, 418)
        CreateAccDialog.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")
        self.btnCrear = QtWidgets.QPushButton(parent=CreateAccDialog)
        self.btnCrear.setGeometry(QtCore.QRect(80, 340, 361, 41))
        self.btnCrear.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCrear.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnCrear.setObjectName("btnCrear")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=CreateAccDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 150, 221, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtCod = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtCod.setEnabled(True)
        self.txtCod.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0,0,0,0.3); \n"
"    color: #e0ffe0;\n"
"    font-size: 16px;\n"
"    border: 1px solid #77dd77;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #aaffaa;\n"
"    font-style: italic;\n"
"}")
        self.txtCod.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.txtCod.setObjectName("txtCod")
        self.verticalLayout.addWidget(self.txtCod)
        self.lblValidAcc = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblValidAcc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblValidAcc.sizePolicy().hasHeightForWidth())
        self.lblValidAcc.setSizePolicy(sizePolicy)
        self.lblValidAcc.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.lblValidAcc.setStyleSheet("QLabel {\n"
"    color: #ff5555;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}")
        self.lblValidAcc.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.LatinAmerica))
        self.lblValidAcc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblValidAcc.setWordWrap(True)
        self.lblValidAcc.setObjectName("lblValidAcc")
        self.verticalLayout.addWidget(self.lblValidAcc)
        self.lblAcc = QtWidgets.QLabel(parent=CreateAccDialog)
        self.lblAcc.setGeometry(QtCore.QRect(130, 110, 281, 21))
        self.lblAcc.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.lblAcc.setObjectName("lblAcc")
        self.lblAppName = QtWidgets.QLabel(parent=CreateAccDialog)
        self.lblAppName.setEnabled(True)
        self.lblAppName.setGeometry(QtCore.QRect(160, 20, 211, 61))
        self.lblAppName.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #77dd77;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.lblAppName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAppName.setObjectName("lblAppName")

        self.retranslateUi(CreateAccDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateAccDialog)

    def retranslateUi(self, CreateAccDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateAccDialog.setWindowTitle(_translate("CreateAccDialog", "Dialog"))
        self.btnCrear.setText(_translate("CreateAccDialog", "Crear"))
        self.txtCod.setPlaceholderText(_translate("CreateAccDialog", "COD"))
        self.lblValidAcc.setText(_translate("CreateAccDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">TextLabel</span></p></body></html>"))
        self.lblAcc.setText(_translate("CreateAccDialog", "Ingrese el codigo de la cuenta a crear"))
        self.lblAppName.setText(_translate("CreateAccDialog", "Crear cuenta"))
