# Form implementation generated from reading ui file 'screens\CreateUser.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateUserDialog(object):
    def setupUi(self, CreateUserDialog):
        CreateUserDialog.setObjectName("CreateUserDialog")
        CreateUserDialog.resize(641, 532)
        CreateUserDialog.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")
        self.lblAppName = QtWidgets.QLabel(parent=CreateUserDialog)
        self.lblAppName.setEnabled(True)
        self.lblAppName.setGeometry(QtCore.QRect(180, 20, 301, 51))
        self.lblAppName.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #77dd77;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.lblAppName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAppName.setObjectName("lblAppName")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=CreateUserDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 110, 421, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtPassword_2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txtPassword_2.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtPassword_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.txtPassword_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword_2.setObjectName("txtPassword_2")
        self.gridLayout.addWidget(self.txtPassword_2, 2, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txtPassword.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtPassword.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 1, 0, 1, 1)
        self.btnShowPwd = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowPwd.sizePolicy().hasHeightForWidth())
        self.btnShowPwd.setSizePolicy(sizePolicy)
        self.btnShowPwd.setMinimumSize(QtCore.QSize(32, 32))
        self.btnShowPwd.setMaximumSize(QtCore.QSize(61, 37))
        self.btnShowPwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnShowPwd.setStyleSheet("QPushButton{\n"
"    border: 1px solid #cccccc;    \n"
"    border-radius: 12px;\n"
"    background-color: transparent;\n"
"    image: url(presentation/icons/closed.png);\n"
"    width: 24px;\n"
"    height: 24px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    image: url(presentation/icons/open.png);\n"
"}\n"
"")
        self.btnShowPwd.setText("")
        self.btnShowPwd.setIconSize(QtCore.QSize(30, 30))
        self.btnShowPwd.setObjectName("btnShowPwd")
        self.gridLayout.addWidget(self.btnShowPwd, 1, 1, 2, 1)
        self.txtUser = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txtUser.setEnabled(True)
        self.txtUser.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtUser.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.txtUser.setObjectName("txtUser")
        self.gridLayout.addWidget(self.txtUser, 0, 0, 1, 2)
        self.lblValidUser = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lblValidUser.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblValidUser.sizePolicy().hasHeightForWidth())
        self.lblValidUser.setSizePolicy(sizePolicy)
        self.lblValidUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.lblValidUser.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}")
        self.lblValidUser.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.LatinAmerica))
        self.lblValidUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblValidUser.setWordWrap(True)
        self.lblValidUser.setObjectName("lblValidUser")
        self.gridLayout.addWidget(self.lblValidUser, 3, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.btnCreateUser = QtWidgets.QPushButton(parent=CreateUserDialog)
        self.btnCreateUser.setGeometry(QtCore.QRect(170, 400, 269, 40))
        self.btnCreateUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCreateUser.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnCreateUser.setObjectName("btnCreateUser")

        self.retranslateUi(CreateUserDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateUserDialog)

    def retranslateUi(self, CreateUserDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateUserDialog.setWindowTitle(_translate("CreateUserDialog", "Dialog"))
        self.lblAppName.setText(_translate("CreateUserDialog", "Crear usuario"))
        self.txtPassword_2.setPlaceholderText(_translate("CreateUserDialog", "Ingrese su contraseña nuevamente"))
        self.txtPassword.setPlaceholderText(_translate("CreateUserDialog", "Ingrese su contraseña"))
        self.txtUser.setPlaceholderText(_translate("CreateUserDialog", "Ingrese su nombre de usuario"))
        self.lblValidUser.setText(_translate("CreateUserDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">TextLabel</span></p></body></html>"))
        self.btnCreateUser.setText(_translate("CreateUserDialog", "Crear usuario"))
