# Form implementation generated from reading ui file 'screens\CreateUser.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateUserDialog(object):
    def setupUi(self, CreateUserDialog):
        CreateUserDialog.setObjectName("CreateUserDialog")
        CreateUserDialog.resize(513, 426)
        CreateUserDialog.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")

        self.retranslateUi(CreateUserDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateUserDialog)

    def retranslateUi(self, CreateUserDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateUserDialog.setWindowTitle(_translate("CreateUserDialog", "Dialog"))
