# Form implementation generated from reading ui file 'screens\Deposit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DepositDialog(object):
    def setupUi(self, DepositDialog):
        DepositDialog.setObjectName("DepositDialog")
        DepositDialog.resize(400, 300)
        DepositDialog.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")

        self.retranslateUi(DepositDialog)
        QtCore.QMetaObject.connectSlotsByName(DepositDialog)

    def retranslateUi(self, DepositDialog):
        _translate = QtCore.QCoreApplication.translate
        DepositDialog.setWindowTitle(_translate("DepositDialog", "Dialog"))
