# Form implementation generated from reading ui file 'screens\Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(798, 600)
        Login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Login.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 130, 391, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtUser = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtUser.setEnabled(True)
        self.txtUser.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtUser.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.txtUser.setObjectName("txtUser")
        self.verticalLayout.addWidget(self.txtUser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtPassword.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtPassword.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout.addWidget(self.txtPassword)
        self.btnShowPwd = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowPwd.sizePolicy().hasHeightForWidth())
        self.btnShowPwd.setSizePolicy(sizePolicy)
        self.btnShowPwd.setMinimumSize(QtCore.QSize(32, 32))
        self.btnShowPwd.setMaximumSize(QtCore.QSize(61, 37))
        self.btnShowPwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnShowPwd.setStyleSheet("QPushButton{\n"
"    border: 1px solid #cccccc;    \n"
"    border-radius: 12px;\n"
"    background-color: transparent;\n"
"    image: url(presentation/icons/closed.png);\n"
"    width: 24px;\n"
"    height: 24px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    image: url(presentation/icons/open.png);\n"
"}\n"
"")
        self.btnShowPwd.setText("")
        self.btnShowPwd.setIconSize(QtCore.QSize(30, 30))
        self.btnShowPwd.setObjectName("btnShowPwd")
        self.horizontalLayout.addWidget(self.btnShowPwd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblValidUser = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblValidUser.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblValidUser.sizePolicy().hasHeightForWidth())
        self.lblValidUser.setSizePolicy(sizePolicy)
        self.lblValidUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.lblValidUser.setStyleSheet("QLabel {\n"
"    color: #ff5555;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    text-decoration: underline;\n"
"}")
        self.lblValidUser.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.LatinAmerica))
        self.lblValidUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblValidUser.setWordWrap(True)
        self.lblValidUser.setObjectName("lblValidUser")
        self.verticalLayout.addWidget(self.lblValidUser)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 360, 271, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLogin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogin.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_2.addWidget(self.btnLogin)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"    color: #77dd77;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btnCreateUser = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnCreateUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCreateUser.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnCreateUser.setObjectName("btnCreateUser")
        self.verticalLayout_2.addWidget(self.btnCreateUser)
        self.lblAppName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAppName.setEnabled(True)
        self.lblAppName.setGeometry(QtCore.QRect(230, 20, 359, 131))
        self.lblAppName.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: #77dd77;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    margin-top: 20px;\n"
"    margin-bottom: 40px;\n"
"}\n"
"")
        self.lblAppName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAppName.setObjectName("lblAppName")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 25))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.txtUser.setPlaceholderText(_translate("Login", "Ingrese su nombre de usuario"))
        self.txtPassword.setPlaceholderText(_translate("Login", "Ingrese su contraseña"))
        self.lblValidUser.setText(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">TextLabel</span></p></body></html>"))
        self.btnLogin.setText(_translate("Login", "Iniciar sesion"))
        self.label.setText(_translate("Login", "No tenes usuario? Crea uno!"))
        self.btnCreateUser.setText(_translate("Login", "Crear usuario"))
        self.lblAppName.setText(_translate("Login", "Wallet APP !"))
