# Form implementation generated from reading ui file 'screens\Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        MainWindow.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 150, 361, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtUser = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtUser.setEnabled(True)
        self.txtUser.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtUser.setObjectName("txtUser")
        self.verticalLayout.addWidget(self.txtUser)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtPassword.setStyleSheet("QLineEdit {\n"
"                background-color: rgba(0,0,0,50) ;\n"
"                color: white;\n"
"                font-size: 15px;\n"
"                background-color: transparente;\n"
"                border: 1px solid #cccccc;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                }")
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout.addWidget(self.txtPassword)
        self.lblValidUser = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblValidUser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblValidUser.sizePolicy().hasHeightForWidth())
        self.lblValidUser.setSizePolicy(sizePolicy)
        self.lblValidUser.setStyleSheet("QLabel {\n"
"    color: #ff5555;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    text-decoration: underline;\n"
"}")
        self.lblValidUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblValidUser.setObjectName("lblValidUser")
        self.verticalLayout.addWidget(self.lblValidUser)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(280, 360, 271, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLogin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogin.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_2.addWidget(self.btnLogin)
        self.lblExistingUser = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.lblExistingUser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExistingUser.sizePolicy().hasHeightForWidth())
        self.lblExistingUser.setSizePolicy(sizePolicy)
        self.lblExistingUser.setStyleSheet("QLabel {\n"
"    color: #ff5555;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    text-decoration: underline;\n"
"}")
        self.lblExistingUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblExistingUser.setObjectName("lblExistingUser")
        self.verticalLayout_2.addWidget(self.lblExistingUser)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"    color: #77dd77;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btnCreateUser = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnCreateUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCreateUser.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnCreateUser.setObjectName("btnCreateUser")
        self.verticalLayout_2.addWidget(self.btnCreateUser)
        self.lblValidUser_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblValidUser_2.setEnabled(True)
        self.lblValidUser_2.setGeometry(QtCore.QRect(230, 20, 359, 131))
        self.lblValidUser_2.setStyleSheet("QLabel {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: #77dd77;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    margin-top: 20px;\n"
"    margin-bottom: 40px;\n"
"}\n"
"")
        self.lblValidUser_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblValidUser_2.setObjectName("lblValidUser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtUser.setPlaceholderText(_translate("MainWindow", "Ingrese su nombre de usuario"))
        self.txtPassword.setPlaceholderText(_translate("MainWindow", "Ingrese su contraseña"))
        self.lblValidUser.setText(_translate("MainWindow", "TextLabel"))
        self.btnLogin.setText(_translate("MainWindow", "Iniciar sesion"))
        self.lblExistingUser.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "No tenes usuario? Crea uno!"))
        self.btnCreateUser.setText(_translate("MainWindow", "Crear usuario"))
        self.lblValidUser_2.setText(_translate("MainWindow", "Wallet APP !"))
