# Form implementation generated from reading ui file 'screens\Sell.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SellDialog(object):
    def setupUi(self, SellDialog):
        SellDialog.setObjectName("SellDialog")
        SellDialog.resize(515, 424)
        SellDialog.setStyleSheet("QWidget {\n"
"                    background-color: #121212;\n"
"                    color: #ffffff;\n"
"                    font-family: Segoe UI;\n"
"                    font-size: 14px;\n"
"                }")
        self.btnSell = QtWidgets.QPushButton(parent=SellDialog)
        self.btnSell.setGeometry(QtCore.QRect(90, 350, 331, 41))
        self.btnSell.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSell.setStyleSheet("QPushButton{\n"
"                        background-color: #77dd77 ;\n"
"                        border: none;\n"
"                        border-radius: 8px;\n"
"                        padding: 10px 18px;\n"
"                        color: #111111;\n"
"                        font-size: 15px;\n"
"                        font-weight: bold;\n"
"                          letter-spacing: 1px;\n"
"                        }\n"
"\n"
"QPushButton:hover{\n"
"                        background-color:#66cc66;       \n"
"                            }\n"
"    \n"
"QPushButton:pressed{\n"
"                        background-color:#55aa55;\n"
"                }")
        self.btnSell.setObjectName("btnSell")
        self.lblCodSell = QtWidgets.QLabel(parent=SellDialog)
        self.lblCodSell.setGeometry(QtCore.QRect(90, 40, 311, 21))
        self.lblCodSell.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.lblCodSell.setObjectName("lblCodSell")
        self.txtCod = QtWidgets.QLineEdit(parent=SellDialog)
        self.txtCod.setEnabled(True)
        self.txtCod.setGeometry(QtCore.QRect(90, 70, 171, 41))
        self.txtCod.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0,0,0,0.3); \n"
"    color: #e0ffe0;\n"
"    font-size: 16px;\n"
"    border: 1px solid #77dd77;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #aaffaa;\n"
"    font-style: italic;\n"
"}")
        self.txtCod.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.txtCod.setObjectName("txtCod")
        self.lblAmountSell = QtWidgets.QLabel(parent=SellDialog)
        self.lblAmountSell.setGeometry(QtCore.QRect(90, 130, 281, 21))
        self.lblAmountSell.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.lblAmountSell.setObjectName("lblAmountSell")
        self.txtAmount = QtWidgets.QLineEdit(parent=SellDialog)
        self.txtAmount.setEnabled(True)
        self.txtAmount.setGeometry(QtCore.QRect(90, 160, 171, 41))
        self.txtAmount.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0,0,0,0.3); \n"
"    color: #e0ffe0;\n"
"    font-size: 16px;\n"
"    border: 1px solid #77dd77;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    qproperty-alignment: \'AlignCenter\'; \n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #aaffaa;\n"
"    font-style: italic;\n"
"}")
        self.txtAmount.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.txtAmount.setObjectName("txtAmount")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=SellDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 230, 421, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblBalance = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBalance.sizePolicy().hasHeightForWidth())
        self.lblBalance.setSizePolicy(sizePolicy)
        self.lblBalance.setAutoFillBackground(False)
        self.lblBalance.setStyleSheet("QLabel {\n"
"    color: #77dd77;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    font-family: Segoe UI;\n"
"    letter-spacing: 0.5px;\n"
"    qproperty-alignment: \'AlignLeft | AlignVCenter\';\n"
"}\n"
"")
        self.lblBalance.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lblBalance.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblBalance.setWordWrap(True)
        self.lblBalance.setObjectName("lblBalance")
        self.verticalLayout.addWidget(self.lblBalance)
        self.lblValidSell = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblValidSell.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblValidSell.sizePolicy().hasHeightForWidth())
        self.lblValidSell.setSizePolicy(sizePolicy)
        self.lblValidSell.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.lblValidSell.setStyleSheet("QLabel {\n"
"    color: #ff5555;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: \'AlignLeft | AlignVCenter\';\n"
"}")
        self.lblValidSell.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.LatinAmerica))
        self.lblValidSell.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblValidSell.setWordWrap(True)
        self.lblValidSell.setObjectName("lblValidSell")
        self.verticalLayout.addWidget(self.lblValidSell)

        self.retranslateUi(SellDialog)
        QtCore.QMetaObject.connectSlotsByName(SellDialog)

    def retranslateUi(self, SellDialog):
        _translate = QtCore.QCoreApplication.translate
        SellDialog.setWindowTitle(_translate("SellDialog", "Dialog"))
        self.btnSell.setText(_translate("SellDialog", "Vender"))
        self.lblCodSell.setText(_translate("SellDialog", "Ingrese el codigo de la moneda a vender"))
        self.txtCod.setPlaceholderText(_translate("SellDialog", "COD"))
        self.lblAmountSell.setText(_translate("SellDialog", "Ingrese el monto que desea vender"))
        self.txtAmount.setPlaceholderText(_translate("SellDialog", "$"))
        self.lblBalance.setText(_translate("SellDialog", "Saldo actual en ARS:"))
        self.lblValidSell.setText(_translate("SellDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">TextLabel</span></p></body></html>"))
