# Form implementation generated from reading ui file 'screens\WalletApp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WalletApp(object):
    def setupUi(self, WalletApp):
        WalletApp.setObjectName("WalletApp")
        WalletApp.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=WalletApp)
        self.centralwidget.setObjectName("centralwidget")
        WalletApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WalletApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        WalletApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WalletApp)
        self.statusbar.setObjectName("statusbar")
        WalletApp.setStatusBar(self.statusbar)

        self.retranslateUi(WalletApp)
        QtCore.QMetaObject.connectSlotsByName(WalletApp)

    def retranslateUi(self, WalletApp):
        _translate = QtCore.QCoreApplication.translate
        WalletApp.setWindowTitle(_translate("WalletApp", "MainWindow"))
